### ISSUE TITLE
logs > 16k block the driver completely for that container

### ISSUE THREAD

**Issue by chrismaes87** [akerouanton/fluentd-async-logger#2]
Docker version 19.03.11, build 42e35e61f3
fluentd-async v0.2

When logging normal sized messages the driver works fine. Printing a (few) message(s) > 16k seem to block the driver completely for that container, the message never comes true (while it did with the normal fluentd driver). Killing that container becomes difficult too.

**Comment by akerouanton** [comment]
Hello @chrismaes87, thanks for reporting this bug. I fixed it in ca439b00. You can now update to v0.3 :wink:
